spring:
  application:
    name: core-service
  datasource:
    url: jdbc:postgresql://${SPRING_DATASOURCE_HOST:localhost}:5432/battery_db
    username: battery_user
    password: ${SPRING_DATASOURCE_PASSWORD:battery_pass}
    hikari:
      maximum-pool-size: 30
      minimum-idle: 5
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate.jdbc.batch_size: 50
      hibernate.order_inserts: true
      hibernate.order_updates: true
  data:
    redis:
      host: ${SPRING_DATA_REDIS_HOST:localhost}
      port: 6379
  rabbitmq:
    host: ${SPRING_RABBITMQ_HOST:localhost}
    port: 5672
    username: battery_rmq
    password: battery_pass

server:
  port: 8080
